[Marketplace Contribution] Exabeam Security Operations Platform - Content Pack Update (#42936)
* [Marketplace Contribution] Exabeam Security Operations Platform - Content Pack Update (#41623)

* "contribution update to pack 'Exabeam Security Operations Platform'"

* pack resubmitted

* resolved rebase conflicts

* Update 1_3_0.md

Deleted the "deleted events comment"

* Update Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml

Co-authored-by: merit-maita <49760643+merit-maita@users.noreply.github.com>

* Update Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml

Co-authored-by: merit-maita <49760643+merit-maita@users.noreply.github.com>

* Update Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml

Co-authored-by: merit-maita <49760643+merit-maita@users.noreply.github.com>

* Update Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml

Co-authored-by: merit-maita <49760643+merit-maita@users.noreply.github.com>

* Update Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml

Co-authored-by: merit-maita <49760643+merit-maita@users.noreply.github.com>

* Update ExabeamSecOpsPlatform.yml

cleaned up yml

* Update Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml

* Update Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml

* first commit

* Apply suggestions from code review

* Update README.md

added descriptions for exabeam-platform-get-events, exabeam-platform-context-table-delete

* Update ExabeamSecOpsPlatform.yml

Deleted the TAGS argument from "exabeam-update-case-details"

* Update ExabeamSecOpsPlatform.py

Updated per review with Merit

* reverted unwanted changes to yml

* Delete pack.zip

* Update README.md, revert

* Update ExabeamSecOpsPlatform.py

Resolved these three:

Error: Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py:1158:68: E711 Comparison to `None` should be `cond is None`
Error: Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py:1215:5: F841 Local variable `keys_to_remove` is assigned to but never used
Error: Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py:1216:5: F841 Local variable `filtered_response` is assigned to but never used

---------

Co-authored-by: David Uhrlaub <90627446+rurhrlaub@users.noreply.github.com>
Co-authored-by: merit-maita <49760643+merit-maita@users.noreply.github.com>
Co-authored-by: Tal <tcarmeli@paloaltonetworks.com>
Co-authored-by: Tal Carmeli <158452762+tcarmeli1@users.noreply.github.com>

* pre-commit edits

---------

Co-authored-by: xsoar-bot <67315154+xsoar-bot@users.noreply.github.com>
Co-authored-by: David Uhrlaub <90627446+rurhrlaub@users.noreply.github.com>
Co-authored-by: merit-maita <49760643+merit-maita@users.noreply.github.com>
Co-authored-by: Tal <tcarmeli@paloaltonetworks.com>
Co-authored-by: Tal Carmeli <158452762+tcarmeli1@users.noreply.github.com>
Co-authored-by: merit-maita <meretmaayta@gmail.com>